[package]
name = "pavia-proto-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"

[dependencies.pavia-proto]
path = ".."

[workspace]
members = ["."]

[[bin]]
name = "varint_decode"
path = "fuzz_targets/varint_decode.rs"
test = false
doc = false
bench = false
